<a href="https://colab.research.google.com/github/OthmaneL4/IA-y-Big-Data-/blob/main/Tarea_Sesion_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#Tarea Sesión 10: Obtención e integración de datos de diferentes fuentes  
## Transporte y Movilidad  

🎯 **Objetivo:**  
Aprender a obtener datos desde distintas fuentes (CSV, APIs, archivos locales, web scraping, bases de datos, etc.) sobre transporte y movilidad, y combinarlos en un único DataFrame.


## 1. Importar librerías
Importa las librerías necesarias para trabajar con pandas, requests, BeautifulSoup, etc.

In [7]:
import pandas as pd
import requests
from bs4 import BeautifulSoup


##  2. Fuente 1: JSON desde URL pública  
Carga el dataset de vehículos.

In [8]:

url_json = "https://raw.githubusercontent.com/vega/vega-datasets/master/data/flights-2k.json"

df_vehicles = pd.read_json(url_json)

display(df_vehicles.head())

                 date  delay  distance origin destination
0 2001-01-14 21:55:00      0       480    SAN         SMF
1 2001-03-26 20:15:00    -11       507    PHX         SLC
2 2001-03-05 14:55:00     -3       714    ELP         LAX
3 2001-01-07 12:30:00     12       342    SJC         SNA
4 2001-01-18 12:00:00      2       373    SMF         LAX


##  3. Fuente 2: API pública  
Usa una API relacionada con transporte, movilidad o tráfico.

In [9]:

import requests
import pandas as pd

url_api = "https://api.citybik.es/v2/networks"

respuesta = requests.get(url_api, timeout=20)
respuesta.raise_for_status()

datos = respuesta.json()

df_bicicletas = pd.json_normalize(datos["networks"])

display(df_bicicletas.head())

,id,name,href,company,gbfs_href,location.latitude,location.longitude,location.city,location.country,system,source,ebikes,license.name,license.url,scooters,instances
0,abu-dhabi-careem-bike,Abu Dhabi Careem BIKE,/v2/networks/abu-dhabi-careem-bike,[Careem],https://dubai.publicbikesystem.net/customer/gb...,24.486600,54.372800,Abu Dhabi,AE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,acces-velo-saguenay,Accès Vélo,/v2/networks/acces-velo-saguenay,[PBSC Urban Solutions],https://saguenay.publicbikesystem.net/customer...,48.433333,-71.083333,Saguenay,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,aduriz,Aduriz en Bici,/v2/networks/aduriz,[Instituto Tecnológico de Castilla y León (ITCL)],NaN,42.929400,-3.488000,Medina de Pomar,ES,bicicard,NaN,NaN,NaN,NaN,NaN,NaN
3,aksu,Aksu,/v2/networks/aksu,[阿克苏公共服务],NaN,41.166400,80.261700,阿克苏市 (Aksu City),CN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,alba,Alba,/v2/networks/alba,[Comunicare S.r.l.],NaN,44.716667,8.083333,Alba,IT,Bicincittà,https://www.bicincitta.com/frmLeStazioni.aspx?...,NaN,NaN,NaN,NaN,NaN


##  4. Fuente 3: Archivo local  
Sube un archivo CSV o Excel con datos complementarios (por ejemplo, uso del transporte público o precios del combustible).

In [14]:
from google.colab import files
uploaded = files.upload()

Saving auto-mpg.csv to auto-mpg.csv

## 5. Fuente 4: Crea un Dataframe relacionado con el tema.

In [15]:
path = "/content/auto-mpg.csv"
df_auto = pd.read_csv(path)
display(df_auto.head())

    mpg  cylinders  displacement  horsepower  weight  acceleration  model-year
0  18.0          8         307.0       130.0    3504          12.0          70
1  15.0          8         350.0       165.0    3693          11.5          70
2  18.0          8         318.0       150.0    3436          11.0          70
3  16.0          8         304.0       150.0    3433          12.0          70
4  17.0          8         302.0       140.0    3449          10.5          70


##  6. Fuente 5: Web Scraping  
Obtén datos desde una página web que los publique en forma de tabla.

In [16]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from io import StringIO

url = "https://en.wikipedia.org/wiki/List_of_countries_by_motor_vehicle_production"

headers = {
    "User-Agent": "Mozilla/5.0"
}

respuesta = requests.get(url, headers=headers, timeout=20)
respuesta.raise_for_status()

soup = BeautifulSoup(respuesta.text, "html.parser")

tablas = soup.find_all("table", class_="wikitable")

print("Tablas encontradas:", len(tablas))

df_web = pd.read_html(StringIO(str(tablas[0])))[0]

display(df_web.head())

Tablas encontradas: 4

         Country   2025[2]   2024[3]   2023[4] 2022[5][6]   2021[7]  \
         Country   2025[2]   2024[3]   2023[4] 2022[5][6]   2021[7]
0          World  96383650  92504338  93546599   85016728  80145988
1          China  34530738  31281592  30160966   27020615  26082220
2  United States  10243844  10562188  10611555   10060339   9167214
3          Japan   8410232   8234681   8997440    7835519   7846955
4          India   6490810   6014691   5851507    5456857   4399112

  2020[8][9] Peak[10][11][12][13][14][15][16]
  2020[8][9]                       Production      Year
0   77621582                         97302534      2017
1   25225242                         34778000      2025
2    8822399                   [17]13,024,978  [18]1999
3    8067557                         13486796      1990
4    3490000                          6490810      2025


##  7. Unir los DataFrames obtenidos  
Combina los distintos DataFrames en uno solo (`df_combinado`) usando `pd.concat()` o `pd.merge()`.

In [17]:

df1 = df_vehicles.copy()
df1["fuente"] = "Vuelos"

df2 = df_bicicletas.copy()
df2["fuente"] = "Bicicletas"

df3 = df_auto.copy()
df3["fuente"] = "Automoviles"

df4 = df_web.copy()
df4["fuente"] = "Produccion de vehiculos"

df_combinado = pd.concat([df1, df2, df3, df4], ignore_index=True)

display(df_combinado.head())

,date,delay,distance,origin,destination,fuente,id,name,href,company,...,"(Country, Country)","(2025[2], 2025[2])","(2024[3], 2024[3])","(2023[4], 2023[4])","(2022[5][6], 2022[5][6])","(2021[7], 2021[7])","(2020[8][9], 2020[8][9])","(Peak[10][11][12][13][14][15][16], Production)","(Peak[10][11][12][13][14][15][16], Year)","(fuente, )"
0,2001-01-14 21:55:00,0.0,480.0,SAN,SMF,Vuelos,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2001-03-26 20:15:00,-11.0,507.0,PHX,SLC,Vuelos,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2001-03-05 14:55:00,-3.0,714.0,ELP,LAX,Vuelos,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2001-01-07 12:30:00,12.0,342.0,SJC,SNA,Vuelos,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2001-01-18 12:00:00,2.0,373.0,SMF,LAX,Vuelos,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN


##  8. Exploración básica del DataFrame combinado  
Usa funciones como `.head()`, `.info()`, `.describe()`, `.max()`, `.min()` para explorar los datos.

In [18]:
display(df_combinado.head())

df_combinado.info()

display(df_combinado.describe())

display(df_combinado.max(numeric_only=True))

display(df_combinado.min(numeric_only=True))

,date,delay,distance,origin,destination,fuente,id,name,href,company,...,"(Country, Country)","(2025[2], 2025[2])","(2024[3], 2024[3])","(2023[4], 2023[4])","(2022[5][6], 2022[5][6])","(2021[7], 2021[7])","(2020[8][9], 2020[8][9])","(Peak[10][11][12][13][14][15][16], Production)","(Peak[10][11][12][13][14][15][16], Year)","(fuente, )"
0,2001-01-14 21:55:00,0.0,480.0,SAN,SMF,Vuelos,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2001-03-26 20:15:00,-11.0,507.0,PHX,SLC,Vuelos,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2001-03-05 14:55:00,-3.0,714.0,ELP,LAX,Vuelos,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2001-01-07 12:30:00,12.0,342.0,SJC,SNA,Vuelos,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2001-01-18 12:00:00,2.0,373.0,SMF,LAX,Vuelos,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3276 entries, 0 to 3275
Data columns (total 39 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   date                                            2000 non-null   datetime64[ns]
 1   delay                                           2000 non-null   float64
 2   distance                                        2000 non-null   float64
 3   origin                                          2000 non-null   object
 4   destination                                     2000 non-null   object
 5   fuente                                          3213 non-null   object
 6   id                                              815 non-null    object
 7   name                                            815 non-null    object
 8   href                                            815 non-null    object
 9   company                                         815 non-null    object
 10  gbfs_href                                       274 non-null    object
 11  location.latitude                               815 non-null    float64
 12  location.longitude                              815 non-null    float64
 13  location.city                                   815 non-null    object
 14  location.country                                815 non-null    object
 15  system                                          563 non-null    object
 16  source                                          213 non-null    object
 17  ebikes                                          46 non-null     object
 18  license.name                                    78 non-null     object
 19  license.url                                     78 non-null     object
 20  scooters                                        2 non-null      object
 21  instances                                       1 non-null      object
 22  mpg                                             398 non-null    float64
 23  cylinders                                       398 non-null    float64
 24  displacement                                    398 non-null    float64
 25  horsepower                                      396 non-null    float64
 26  weight                                          398 non-null    float64
 27  acceleration                                    398 non-null    float64
 28  model-year                                      398 non-null    float64
 29  (Country, Country)                              63 non-null     object
 30  (2025[2], 2025[2])                              45 non-null     object
 31  (2024[3], 2024[3])                              63 non-null     object
 32  (2023[4], 2023[4])                              63 non-null     object
 33  (2022[5][6], 2022[5][6])                        63 non-null     object
 34  (2021[7], 2021[7])                              63 non-null     object
 35  (2020[8][9], 2020[8][9])                        63 non-null     object
 36  (Peak[10][11][12][13][14][15][16], Production)  63 non-null     object
 37  (Peak[10][11][12][13][14][15][16], Year)        63 non-null     object
 38  (fuente, )                                      63 non-null     object
dtypes: datetime64[ns](1), float64(11), object(27)
memory usage: 998.3+ KB

,date,delay,distance,location.latitude,location.longitude,mpg,cylinders,displacement,horsepower,weight,acceleration,model-year
count,2000,2000.000000,2000.000000,815.000000,815.000000,398.000000,398.000000,398.000000,396.000000,398.000000,398.000000,398.000000
mean,2001-02-15 19:52:40.920000,8.027500,496.843500,42.270458,10.791792,23.514573,5.454774,193.425879,104.189394,2970.424623,15.568090,76.010050
min,2001-01-01 06:25:00,-33.000000,108.000000,-34.630665,-157.856000,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000
25%,2001-01-24 19:27:30,-5.000000,283.000000,39.735025,-0.346781,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000
50%,2001-02-16 17:47:00,0.000000,366.000000,45.165600,9.654954,23.000000,4.000000,148.500000,92.000000,2803.500000,15.500000,76.000000
75%,2001-03-09 07:52:00,12.000000,590.000000,49.464950,17.373840,29.000000,8.000000,262.000000,125.000000,3608.000000,17.175000,79.000000
max,2001-03-31 20:35:00,250.000000,2277.000000,68.166900,141.134300,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000
std,NaN,24.728657,352.533469,13.150336,51.772067,7.815984,1.701004,104.269838,38.402030,846.841774,2.757689,3.697627

delay                  250.0000
distance              2277.0000
location.latitude       68.1669
location.longitude     141.1343
mpg                     46.6000
cylinders                8.0000
displacement           455.0000
horsepower             230.0000
weight                5140.0000
acceleration            24.8000
model-year              82.0000
dtype: float64

delay                  -33.000000
distance               108.000000
location.latitude      -34.630665
location.longitude    -157.856000
mpg                      9.000000
cylinders                3.000000
displacement            68.000000
horsepower              46.000000
weight                1613.000000
acceleration             8.000000
model-year              70.000000
dtype: float64


##  9. Conclusión  
Escribe un resumen breve (5-10 líneas) sobre:
- Qué fuentes de datos has utilizado.  
- Cómo los has combinado.  
- Qué tipo de información contiene el DataFrame final.  
- Qué dificultades has tenido y cómo las resolviste.


##  9. Conclusión  
Escribe un resumen breve (5-10 líneas) sobre:
- Qué fuentes de datos has utilizado.  
- Cómo los has combinado.  
- Qué tipo de información contiene el DataFrame final.  
- Qué dificultades has tenido y cómo las resolviste.

En esta práctica hemos trabajado con diferentes fuentes de datos relacionadas con el transporte y la movilidad. Para obtener la información hemos utilizado archivos JSON, una API pública de bicicletas, archivos CSV y web scraping para extraer datos de una página de Wikipedia.

Una vez obtenidos los datos, los hemos convertido en DataFrames utilizando la librería Pandas. Después, hemos utilizado `pd.concat()` para unirlos en un único DataFrame llamado `df_combinado`, añadiendo una columna para identificar de qué fuente procede cada registro.

El DataFrame final contiene información sobre vuelos, bicicletas públicas, características de automóviles y producción de vehículos en diferentes países. Durante la práctica hemos tenido algunos problemas con la carga de archivos CSV y con el acceso a determinadas páginas web, pero los hemos solucionado revisando las rutas de los archivos y utilizando otra página para realizar el web scraping.

En general, esta práctica nos ha servido para aprender a obtener, organizar y combinar datos procedentes de diferentes fuentes utilizando Python.